#!/usr/bin/env tsx
/**
 * Generates docs/compatibility.md from real package.json values.
 * Run via `pnpm run docs:compat`. CI verifies the file is up to date.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const OUT = join(ROOT, "docs/compatibility.md");

type PkgJson = {
  name: string;
  version: string;
  type?: string;
  engines?: Record<string, string>;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  packageManager?: string;
};

function readJson(path: string): PkgJson {
  return JSON.parse(readFileSync(path, "utf8"));
}

const rootPkg = readJson(join(ROOT, "package.json"));
const packagesDir = join(ROOT, "packages");
const packages = readdirSync(packagesDir)
  .map((name) => join(packagesDir, name, "package.json"))
  .filter((p) => existsSync(p))
  .map(readJson)
  .filter((p) => p.name.startsWith("@junando/"))
  .sort((a, b) => a.name.localeCompare(b.name));

const cdkStack = readFileSync(
  join(ROOT, "packages/cdk/lib/junando-stack.ts"),
  "utf8",
);
const runtimeMatch = cdkStack.match(/lambda\.Runtime\.(NODEJS_\d+_X)/);
const lambdaRuntime = runtimeMatch?.[1]
  ? runtimeMatch[1].replace("NODEJS_", "nodejs").replace("_X", ".x").toLowerCase()
  : "unknown";

const nodeEngine = rootPkg.engines?.node ?? "unspecified";
const pnpmEngine = rootPkg.engines?.pnpm ?? "unspecified";
const packageManager = rootPkg.packageManager?.split("+")[0] ?? "unspecified";
const nodeMajor = nodeEngine.match(/\d+/)?.[0] ?? "?";

function moduleFormat(pkg: PkgJson): { esm: boolean; cjs: boolean; note: string } {
  const isEsm = pkg.type === "module";
  const pkgDir = join(ROOT, "packages", pkg.name.replace("@junando/", ""));
  // Check tsdown first, then tsup as fallback
  for (const configName of ["tsdown.config.ts", "tsup.config.ts"]) {
    const configPath = join(pkgDir, configName);
    if (existsSync(configPath)) {
      const cfg = readFileSync(configPath, "utf8");
      const hasCjs = /["']cjs["']/.test(cfg);
      const hasEsm = /["']esm["']/.test(cfg);
      const tool = configName.startsWith("tsdown") ? "tsdown" : "tsup";
      if (hasCjs && hasEsm) return { esm: true, cjs: true, note: `Dual build via ${tool}` };
      if (hasEsm) return { esm: true, cjs: false, note: `ESM only (${tool})` };
      if (hasCjs) return { esm: false, cjs: true, note: `CJS only (${tool})` };
      break;
    }
  }
  return {
    esm: isEsm,
    cjs: !isEsm,
    note: isEsm ? "ESM only" : "CJS only",
  };
}

const keyDeps = new Set([
  "ioredis",
  "zod",
  "@aws-sdk/client-sqs",
  "@aws-sdk/client-ssm",
  "@anthropic-ai/sdk",
  "@google/generative-ai",
  "prom-client",
]);

const depUsage = new Map<string, { range: string; users: string[] }>();
for (const pkg of packages) {
  for (const [dep, range] of Object.entries(pkg.dependencies ?? {})) {
    if (!keyDeps.has(dep)) continue;
    const entry = depUsage.get(dep) ?? { range, users: [] };
    entry.users.push(pkg.name);
    depUsage.set(dep, entry);
  }
}

const pkgRows = packages
  .map((p) => {
    const fmt = moduleFormat(p);
    return `| \`${p.name}\` | ${fmt.esm ? "✅" : "❌"} | ${fmt.cjs ? "✅" : "❌"} | ${fmt.note} |`;
  })
  .join("\n");

const versionRows = packages
  .map((p) => `| \`${p.name}\` | ${p.version} | — |`)
  .join("\n");

const depRows = [...depUsage.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(
    ([dep, info]) =>
      `| \`${dep}\` | \`${info.range}\` | ${info.users.map((u) => `\`${u}\``).join(", ")} |`,
  )
  .join("\n");

const md = `<!-- AUTO-GENERATED by scripts/generate-compat-matrix.ts. Do not edit by hand. Run \`pnpm run docs:compat\`. -->
# Compatibility Matrix

## Node.js

| Version | Status     | Notes                              |
|---------|------------|------------------------------------|
| ${nodeMajor}.x    | ✅ Supported | CI target; Lambda runtime          |
| < ${nodeMajor}    | ❌ Unsupported | \`engines\` field enforces \`${nodeEngine}\` |

> The root \`package.json\` declares \`"node": "${nodeEngine}"\`. pnpm will refuse installs on older runtimes.

## Module Format

| Package           | ESM | CJS | Notes                                  |
|-------------------|-----|-----|----------------------------------------|
${pkgRows}

> All packages target **ES2022** (\`tsconfig\` \`target\`). TypeScript declarations are emitted for both ESM and CJS where applicable.

## AWS Lambda Runtime

| Runtime      | Status       | Notes                                    |
|--------------|--------------|------------------------------------------|
| \`${lambdaRuntime}\` | ✅ Supported  | CDK deploys this runtime for all Lambdas |
| Others       | ❌ Not tested | CDK stack hardcodes \`${lambdaRuntime}\` |

## Package Versions

| Package             | Current | Minimum peer |
|---------------------|---------|--------------|
${versionRows}

All packages are versioned in lockstep. Install the same version across packages to avoid type mismatches.

## Key Runtime Dependencies

| Dependency          | Version range | Used by                        |
|---------------------|---------------|--------------------------------|
${depRows}

## pnpm

| Version | Status     |
|---------|------------|
| \`${packageManager}\` | ✅ Pinned via \`packageManager\` |
| ${pnpmEngine} | ✅ Supported (engines) |
| < 9     | ❌ Unsupported |

## NestJS

Junando does not depend on NestJS. The packages are framework-agnostic and can be used in any Node.js server (Express, Fastify, NestJS, plain Lambda handlers, etc.).
`;

if (process.argv.includes("--check")) {
  const existing = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (existing !== md) {
    console.error(
      "docs/compatibility.md is out of date. Run `pnpm run docs:compat` and commit the result.",
    );
    process.exit(1);
  }
  console.log("docs/compatibility.md is up to date.");
} else {
  writeFileSync(OUT, md);
  console.log(`Wrote ${OUT}`);
}
